---
name: test

# yamllint disable-line rule:truthy
on:
  pull_request:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read

# If action is already running, cancel the previous run
concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Install dependencies
        if: ${{ hashFiles('Makefile') != '' }}
        run: |
          sudo apt-get update
          sudo apt-get install -y make bats

      - name: Run tests
        if: ${{ hashFiles('Makefile') != '' }}
        run: make test
